language: python
dist: xenial
sudo: false
env:
  - ES_VERSION=6.5.4 ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz ELASTICSEARCH_ENABLED=True
before_install:
  - wget ${ES_DOWNLOAD_URL}
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  - echo "ES_HOME=`realpath elasticsearch-${ES_VERSION}`" >> .env
  - cat .env

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -e .[dev]
script:
  - pytest --cov=karp5 --cov-report=term karp5/tests
after_success:
  - codecov
  - coveralls
